//
//  DetailsViewForAPIDesignGuidelines.swift
//  iDevNotes
//
//  Created by wangqiyang on 2026/1/3.
//

import SwiftUI

struct DetailsViewForAPIDesignGuidelines: View {
    var body: some View {
        H2("基础知识")
        Text(
            "在使用点上的清晰性是你最重要的目标。实体（如方法和属性）只被声明一次，但会被反复使用。设计 API 以使这些用法清晰且简明。当评估一个设计时，单独阅读声明往往不足；务必评估一个用例，以确保在上下文中看起来清晰。"
        )
        Text(
            "**清晰性比简洁性更为重要**。尽管 Swift 代码可以很紧凑，但使代码尽可能少的字符数并非目标。Swift 代码中的简洁性，在出现时，是强类型系统和天然减少样板代码的特性的副作用。"
        )
        Text("为每个声明编写文档注释。编写文档所获得的洞察力可能对你的设计产生深远影响，因此不要拖延。")
        CalloutView(
            .warning,
            content: "如果你在用简单的术语描述你的 API 的功能时遇到困难，你可能设计错了 API。"
        )
        Text("使用 Swift 的 Markdown 方言。")
        Text("以对被声明实体的摘要作为起点。通常，可以仅通过声明及其摘要来完全理解一个 API。")
        DisclosureGroup {
            VStack(alignment: .leading, spacing: 12) {
                CodeAndPreviewView(
                    """
                    /// Returns a "view" of `self` containing the same elements in
                    /// reverse order.
                    func reversed() -> ReverseCollection
                    """
                )
                Text("专注于摘要；这是最重要的部分。许多出色的文档注释仅仅由一个极好的摘要组成。")
                Text("尽可能使用一个句子片段，以句号结尾。不要使用完整句子。")
                DisclosureGroup {
                    VStack(alignment: .leading, spacing: 12) {
                        CodeAndPreviewView(
                            """
                            /// Inserts `newHead` at the beginning of `self`.
                            mutating func prepend(_ newHead: Int)
                            /// Returns a `List` containing `head` followed by the elements
                            /// of `self`.
                            func prepending(_ head: Element) -> List

                            /// Removes and returns the first element of `self` if non-empty;
                            /// returns `nil` otherwise.
                            mutating func popFirst() -> Element?
                            """
                        )
                        Text("注：在极少数情况下，如上面的 popFirst ，摘要由多个以分号分隔的句子片段组成。")
                    }
                } label: {
                    Text("描述一个函数或方法的作用及其返回值，省略空值效应和 Void 返回值：")
                        .multilineTextAlignment(.leading)
                }
                .foregroundStyle(.primary)
                DisclosureGroup {
                    CodeAndPreviewView(
                        """
                        /// Accesses the `index`th element.
                        subscript(index: Int) -> Element { get set }
                        """
                    )
                } label: {
                    Text("描述下标访问的内容：")
                        .multilineTextAlignment(.leading)
                }
                .foregroundStyle(.primary)
                DisclosureGroup {
                    CodeAndPreviewView(
                        """
                        /// Creates an instance containing `n` repetitions of `x`.
                        init(count n: Int, repeatedElement x: Element)
                        """
                    )
                } label: {
                    Text("描述初始化器会创建什么：")
                        .multilineTextAlignment(.leading)
                }
                .foregroundStyle(.primary)
                DisclosureGroup {
                    CodeAndPreviewView(
                        """
                        /// A collection that supports equally efficient insertion/removal
                        /// at any position.
                        struct List {
                        /// The element at the beginning of `self`, or `nil` if self is
                        /// empty.
                        var first: Element?
                        ...
                        """
                    )
                } label: {
                    Text("对于所有其他声明，描述所声明实体的性质。")
                        .multilineTextAlignment(.leading)
                }
                .foregroundStyle(.primary)
            }
        } label: {
            Text("以对被声明实体的摘要作为起点。通常，可以仅通过声明及其摘要来完全理解一个 API。")
                .multilineTextAlignment(.leading)
        }
        .foregroundStyle(.primary)
        Text("可选地，继续撰写一个或多个段落和项目符号。段落之间用空行分隔，并使用完整句子。")
        CodeAndPreviewView(
            #"""
            /// Writes the textual representation of each    ← Summary
            /// element of `items` to the standard output.
            ///                                              ← Blank line
            /// The textual representation for each item `x` ← Additional discussion
            /// is generated by the expression `String(x)`.
            ///
            /// - Parameter separator: text to be printed    ⎫
            ///   between items.                             ⎟
            /// - Parameter terminator: text to be printed   ⎬ Parameters section
            ///   at the end.                                ⎟
            ///                                              ⎭
            /// - Note: To print without a trailing          ⎫
            ///   newline, pass `terminator: ""`             ⎟
            ///                                              ⎬ Symbol commands
            /// - SeeAlso: `CustomDebugStringConvertible`,   ⎟
            ///   `CustomStringConvertible`, `debugPrint`.   ⎭
            public func print(_ items: Any..., separator: String = " ", terminator: String = "\n")
            """#
        )
        Text("在适当的情况下，使用公认的符号文档标记元素来添加超出摘要的信息。")
        DisclosureGroup {

        } label: {
            Text("认识并使用带符号命令语法的已认可的要点列表。流行的开发工具，如 Xcode，对以以下关键词开头的要点列表给予特殊处理：")
                .multilineTextAlignment(.leading)
        }
        .foregroundStyle(.primary)
        H2("命名")
        H3("促进清晰使用")
        DisclosureGroup {
            VStack(alignment: .leading, spacing: 12) {
                Text("例如，考虑一个在集合中删除给定位置处元素的方法。")
                CodeAndPreviewView(
                    """
                    extension List {
                        public mutating func remove(at position: Index) -> Element
                    }
                    employees.remove(at: x)
                    """
                )
                Text(
                    "如果我们在方法签名中省略单词 at ，这可能会让读者以为该方法是在搜索并移除等于 x 的元素，而不是使用 x 来指示要移除的元素的位置。"
                )
                CodeAndPreviewView(
                    "employees.remove(x) // unclear: are we removing x?"
                )
            }
        } label: {
            Text("包含所有在读取代码时为避免歧义而需要使用的单词，尤其是在名称被使用的情况下。")
                .multilineTextAlignment(.leading)
        }
        .foregroundStyle(.primary)
        DisclosureGroup {
            VStack(alignment: .leading, spacing: 12) {
                Text(
                    "可能需要更多的词语来阐明意图或消除歧义，但那些与读者已掌握的信息重复的词语应当被省略。特别是，应当省略那些仅仅重复类型信息的词语。"
                )
                CodeAndPreviewView(
                    """
                    public mutating func removeElement(_ member: Element) -> Element?

                    allViews.removeElement(cancelButton)
                    """
                )
                Text("在这种情况下， `Element` 这个词在调用处不会增加任何显著的内容。这个 API 会更好：")
                CodeAndPreviewView(
                    """
                    public mutating func remove(_ member: Element) -> Element?
                    """
                )
                Text("有时，为了消除歧义，重复类型信息是必要的，但通常最好使用描述参数作用而不是其类型的词语。详情请见下一条。")
            }
        } label: {
            Text("省略多余的词语。名称中的每一个词在使用处都应传达重要信息。")
                .multilineTextAlignment(.leading)
        }
        .foregroundStyle(.primary)
        DisclosureGroup {
            VStack(alignment: .leading, spacing: 12) {
                CodeAndPreviewView(
                    """
                    var string = "Hello"
                    protocol ViewController {
                        associatedtype ViewType : View
                    }
                    class ProductionLine {
                        func restock(from widgetFactory: WidgetFactory)
                    }
                    """
                )
            }
        } label: {
            Text("**根据其作用命名变量、参数和关联类型**，而不是根据其类型约束。")
                .multilineTextAlignment(.leading)
        }
        .foregroundStyle(.primary)
    }
}

struct CalloutView: View {
    let type: CalloutType
    let content: String

    init(_ type: CalloutType, content: String) {
        self.type = type
        self.content = content
    }

    enum CalloutType {
        case warning
        case success
        case failure
        case info
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Image(systemName: "exclamationmark.circle")
                .foregroundStyle(.orange)
            Text(content)
                .frame(
                    maxWidth: .infinity,
                    alignment: .leading
                )
        }
        .padding()
        .glassEffect(
            .regular.tint(.orange.opacity(0.35)),
            in: .rect(cornerRadius: 20)
        )
    }
}

#Preview {
    ScrollView {
        LazyVStack(alignment: .leading, spacing: 12) {
            DetailsViewForAPIDesignGuidelines()
        }
        .padding()
    }
}
